# -------------------------------------------
# Variance project core services - dev server
# -------------------------------------------
services:

  # Laravel
  # ----------------------------------------
  laravel:
    build:
      context: ./laravel
    container_name: laravel
    volumes:
      - ./laravel/app:/var/www/html
    working_dir: /var/www/html
    environment:
      - PHP_MEMORY_LIMIT=512M
    ports:
      - "8000:8000"

  # MariaDB
  # ----------------------------------------
  mariadb:
    image: mariadb:11.5.2
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: variance
      MYSQL_USER: variance_user
      MYSQL_PASSWORD: variance_password
    volumes:
      - dbdata:/var/lib/mysql

  # phpMyAdmin
  # ----------------------------------------
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"

# Named volumes
# -----------------------------------------
volumes:
  dbdata:
